version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - jruz
  assignees:
  - jruz
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.3
  - dependency-name: shadow-cljs
    versions:
    - 2.11.15
    - 2.11.16
    - 2.11.17
    - 2.11.18
    - 2.11.19
    - 2.11.20
    - 2.11.21
    - 2.11.22
    - 2.11.23
    - 2.11.24
    - 2.11.25
    - 2.11.26
    - 2.12.0
    - 2.12.1
    - 2.12.2
    - 2.12.3
    - 2.12.4
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: stylelint-scss
    versions:
    - 3.18.0
  - dependency-name: react-dom
    versions:
    - 16.13.0
