version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - jruz
    default_assignees:
      - jruz
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
